name = "mercury-gate"
main = "src/index.js"
compatibility_date = "2026-08-01"

[vars]
BACKEND_URL = "https://mercury-ingest.rpgm.tools/ingest"

[[routes]]
pattern = "mercury.rpgm.tools"
custom_domain = true
